name: Deploy Vite App to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Install Node.js
        uses: actions/setup-node@v4.1.0
        with:
          node-version: "22"

      - name: Install dependencies
        run: yarn install

      - name: Build project
        run: yarn build

      - name: Upload Github Pages Artifact
        uses: actions/upload-pages-artifact@v3.0.1

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4.0.5
